*** Begin Patch
*** Update File: lib/llm/router.ts
@@
-const MODEL_ROUTING: Record<LLMTask, LLMProvider> = {
-  code: 'openai',
-  builder: 'openai',
-  estimate: 'openai',
-  seo: 'openai',
-  reasoning: 'claude',
-  automation: 'claude',
-  voice: 'openai',
-  chat: 'openai',
-  fast: 'local',
-};
+const MODEL_ROUTING: Record<LLMTask, LLMProvider> = {
+  code: 'openai',
+  builder: 'openai',
+  // Ensure estimates use local-only models for takeoffs
+  estimate: 'local',
+  seo: 'openai',
+  reasoning: 'claude',
+  automation: 'claude',
+  voice: 'openai',
+  chat: 'openai',
+  fast: 'local',
+};
@@
-function localFallback(req: LLMRequest): LLMResponse {
-  if (req.task === 'estimate') {
-    // Parse estimate prompt for key details
-    const tradesMatch = req.prompt.match(/Trades: (.*?)\\./i) || req.prompt.match(/trades?:? (.*?)\\./i);
-    const trades = tradesMatch ? tradesMatch[1].trim() : 'project trades';
-    const totalMatch = req.prompt.match(/Total: \\$(\\d+(?:,\\d{3})*)/i);
-    const total = totalMatch ? totalMatch[1] : '$XX,XXX';
-    const sqftMatch = req.prompt.match(/Square footage: (\\d+)/i);
-    const sqft = sqftMatch ? sqftMatch[1] : 'X,XXX';
-    
-    return {
-      text: `Professional construction estimate summary:\n\\n**Total Project Cost: ${total}**\\n**Scope: ${sqft} sqft, ${trades}**\\n\\nThis bid includes complete material, labor, overhead (12%)[...]",
-      provider: 'local',
-      model: 'estimator-local',
-    };
-  }
-  
-  return {
-    text: `[Local model] Received task "${req.task}". Configure OPENAI_API_KEY or ANTHROPIC_API_KEY for full AI responses.`,
-    provider: 'local',
-    model: 'local-fallback',
-  };
-}
+function localFallback(req: LLMRequest): LLMResponse {
+  if (req.task === 'estimate') {
+    // Build a structured, parseable fallback summary for estimates so the API and UI
+    // never receive the generic "[Local model]" message that breaks parsing.
+    // Attempt to extract simple fields from the prompt; if not present, leave undefined.
+    const tradesMatch = req.prompt.match(/Trades: (.*?)\\.|trades?:? (.*?)\\./i);
+    const trades = tradesMatch ? (tradesMatch[1] || tradesMatch[2]).trim() : undefined;
+    const totalMatch = req.prompt.match(/Total: \\$(\\d+(?:,\\d{3})*)/i);
+    const total = totalMatch ? Number(totalMatch[1].replace(/,/g, '')) : undefined;
+    const sqftMatch = req.prompt.match(/(Square footage|sqft|square feet):?\\s*(\\d[\d,]*)/i);
+    const sqft = sqftMatch ? Number(sqftMatch[2].replace(/,/g, '')) : undefined;
+
+    const humanTextParts: string[] = [];
+    if (typeof total === 'number') humanTextParts.push(`Total Project Cost: $${total.toLocaleString()}`);
+    if (typeof sqft === 'number' || trades) humanTextParts.push(`Scope: ${sqft ? `${sqft.toLocaleString()} sqft` : ''}${sqft && trades ? ', ' : ''}${trades ?? ''}`);
+    if (!humanTextParts.length) humanTextParts.push('Estimate summary generated by local estimator.');
+
+    // Provide a compact JSON-like wrapper in the text so clients that try to parse JSON
+    // can extract a stable object. Also include a readable summary string.
+    const summaryObj = {
+      provider: 'local',
+      model: 'estimator-local',
+      total: typeof total === 'number' ? total : null,
+      sqft: typeof sqft === 'number' ? sqft : null,
+      trades: trades ?? null,
+      text: humanTextParts.join(' | '),
+    };
+
+    return {
+      text: `ESTIMATE_SUMMARY:${JSON.stringify(summaryObj)}`,
+      provider: 'local',
+      model: 'estimator-local',
+    };
+  }
+
+  return {
+    text: `[Local model] Received task "${req.task}". Configure OPENAI_API_KEY or ANTHROPIC_API_KEY for full AI responses.`,
+    provider: 'local',
+    model: 'local-fallback',
+  };
+}
*** End Patch