*** Begin Patch
*** Update File: app/api/estimate/generate/route.ts
@@
-    // AI summary
-    let summary = '';
-    try {
-      summary = await llm(
-        `Summarize this multi-trade construction estimate for a contractor in 3 sentences. Trades: ${tradeEstimates.map((t) => t.tradeName).join(', ')}. Total: $${grandTotal.toFixed(0)}. Square f[...]
-        'estimate',
-        'You are a senior construction estimator. Give brief, accurate summaries.'
-      );
-    } catch {
-      summary = `Estimate for ${tradeEstimates.map((t) => t.tradeName).join(', ')} at ${sqft.toLocaleString()} sqft. Grand total: $${grandTotal.toLocaleString(undefined, { maximumFractionDigits: [...]
-    }
+    // AI summary — prefer local estimator. If the LLM returns a structured fallback
+    // (ESTIMATE_SUMMARY:...), parse it. Otherwise use the returned text. If anything
+    // looks like the generic local model marker or is invalid, build a deterministic
+    // summary from computed values so the UI never receives an error placeholder.
+    let summary = '';
+    let llmText = '';
+    try {
+      llmText = await llm(
+        `Summarize this multi-trade construction estimate for a contractor in 3 sentences. Trades: ${tradeEstimates.map((t) => t.tradeName).join(', ')}. Total: $${grandTotal.toFixed(0)}. Square footage: ${sqft}.`,
+        'estimate',
+        'You are a senior construction estimator. Give brief, accurate summaries.'
+      );
+
+      // Detect our structured fallback prefix
+      if (llmText && llmText.startsWith('ESTIMATE_SUMMARY:')) {
+        try {
+          const jsonPart = llmText.replace('ESTIMATE_SUMMARY:', '').trim();
+          const parsed = JSON.parse(jsonPart);
+          summary = parsed.text || `Estimate for ${tradeEstimates.map((t) => t.tradeName).join(', ')} — $${grandTotal.toLocaleString()}`;
+        } catch {
+          summary = llmText;
+        }
+      } else {
+        summary = llmText;
+      }
+    } catch (e) {
+      // llm() threw — fall through to deterministic summary
+      llmText = '';
+    }
+
+    // If we got an empty summary or it contains the generic local marker, build a deterministic one
+    if (!summary || summary.includes('[Local model]') || summary.includes('Estimate summary generated by local estimator')) {
+      summary = `Estimate for ${tradeEstimates.map((t) => t.tradeName).join(', ')} at ${sqft.toLocaleString()} sqft. Grand total: $${grandTotal.toLocaleString(undefined, { maximumFractionDigits: 0 })}. Timeline: ${timeline.join(', ')}.`;
+    }
+
+    // Log provider / llm response for debugging (server logs)
+    try {
+      // eslint-disable-next-line no-console
+      console.info('[estimate/generate] llmText:', llmText ? llmText.slice(0, 400) : '<empty>');
+    } catch {
+      // ignore logging errors
+    }
*** End Patch